### ISSUE TITLE
actions.php & buttons.php error site dont load HTTP ERROR 500

### ISSUE THREAD

**Issue by GorlikItsMe** [gumslone/GumCP#13]
HTTP ERROR 500 when i try go in to this sites (actions.php & buttons.php)

**Comment by gumslone** [comment]
Hi, this is because php-ssh2 is not installed:

For PHP 7 use this:

```sudo apt-get install php7.0-ssh2```

For PHP 7.1 use this:

```sudo apt-get install php7.1-ssh2```

Or try this command:

```sudo apt-get install php-ssh2```

**Comment by jelmervisser** [comment]
Hi,

I had to manually install the libssh2 package and the php-ssh2 package because I use php7.2.

**libssh2:**
wget https://www.libssh2.org/download/libssh2-1.8.0.tar.gz
tar vxzf libssh2-1.8.0.tar.gz
cd libssh2-1.8.0
./configure
make
sudo make install

**php-ssh2:**
wget https://pecl.php.net/get/ssh2-1.1.2.tgz
cd ssh2-1.1.2
phpize
./configure --with-ssh2
make
sudo make install

after that add "extension=ssh2.so" to your php.ini

@gumslone I think you can close this issue as it is not a issue with your panel ;-)

**Comment by gumslone** [comment]
Hi, thanks for sharing your install instructions.
